### ISSUE TITLE
 This action cannot be completed at this time (-22411)

### ISSUE THREAD

**Issue by johnsonjh** [SideStore/SideServer-for-Linux#8]
```
Received auth response status code: 200
Alert: Could not install AltStore.ipa to unknown.
    This action cannot be completed at this time (-22411)
Press any key to continue...
```

If I try it again it gives the same message or requires a password reset.

Any ideas?

**Comment by Spidy123222** [comment]
> ```
> 
> Received auth response status code: 200
> 
> Alert: Could not install AltStore.ipa to unknown.
> 
>     This action cannot be completed at this time (-22411)
> 
> Press any key to continue...
> 
> ```
> 
> 
> 
> If I try it again it gives the same message or requires a password reset.
> 
> 
> 
> Any ideas?

Traditionally -22411 means to have your account on the device logged in your installing to or from. I suggest using sideloader as it will likely replace this repo at some point. https://github.com/Dadoum/Sideloader

After installing sidestore just login and sideload sidestore ipa inside sidestore to fix a issue and your good then.

**Comment by johnsonjh** [comment]
I'll give it a shot, thanks.  I guess we can close this for now.
